#ddev-generated
images:
  - ddev/ddev-webserver
  - ddev/ddev-dbserver-mysql-8.0
  - ddev/ddev-dbserver-mysql-5.7
  - ddev/ddev-dbserver-mariadb-10.11
  - ddev/ddev-ssh-agent
  - ddev/ddev-traefik-router
  - ddev/ddev-utilities:latest
  - ddev/ddev-xhgui:latest
  - solr:8
  - busybox:stable
  - adminer:latest
