#ddev-generated
images:
  web: ddev/ddev-webserver
  db: ddev/ddev-dbserver-mysql-5.7
  sshagent: ddev/ddev-ssh-agent
  router: ddev/ddev-traefik-router
  solr-8: solr:8
  busybox-stable: busybox:stable
