registry_images:
  - ddev/ddev-webserver
  - ddev/ddev-dbserver-mysql-5.7
  - ddev/ddev-ssh-agent
  - ddev/ddev-traefik-router
  - solr:8
  - busybox:stable

hooks:
  pre-start:
    - exec-host: export DDEV_VERSION=$(ddev --version | awk '{print $3}')
    - exec-host: docker login $registry_url -u $registry_user -p $registry_pass