#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EMV_TARGET="${SCRIPT_DIR%/scripts}/.env"

if [[ -f "$ENV_TARGET" ]]; then
  echo "Existing .env detected - skipping credential prompt."
  exit 0
fi

echo "Configure your private Docker registry mirror."
read -rp "Registry URL (e.g registry.example.com) : " REGISTRY_URL
read -rp "Registry username :                       " REGISTRY_USER
read -srp "Registry password (hidden) :             " REGISTRY_PASS
printf "\n"

# Choose backend
PS3="Select back-end (default 1): "
select opt in "rewrite (no sudo, default)" "daemon (requires sudo)"; do
  case $REPLY in
    1|"") BACKEND="rewrite"; break;;
    2) BACKEND="daemon"; break;;
    *) echo "Choose 1 or 2";;
  esac
done

cat > "$ENV_TARGET" <<EOF
# Auto-generated by ddev-custom-image-registry on $(date)
REGISTRY_URL=$REGISTRY_URL
REGISTRY_USER=$REGISTRY_USER
REGISTRY_PASS=$REGISTRY_PASS
BACKEND=$BACKEND
EOF
chmod 600 "$ENV_TARGET"
echo "Credentials saved to $ENV_TARGET (chmod 600)."
