#!/usr/bin/env bash
set -euo pipefail
PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo "$PWD")"
LOCAL_PLUGIN_DIR="$PROJECT_ROOT/.ddev/private-registry"
GLOBAL_PLUGIN_DIR="$HOME/.ddev/plugins/ddev-private-registry"

PLUGIN_DIR="$LOCAL_PLUGIN_DIR"
[[ -f "$PLUGIN_DIR/.env" ]] || PLUGIN_DIR="$GLOBAL_PLUGIN_DIR"
source "$PLUGIN_DIR/.env"
CONFIG_FILE="$PROJECT_ROOT/.ddev/private-registry.yml"

# login (token may expire)
echo "$REGISTRY_PASS" | docker login "$REGISTRY_URL" -u "$REGISTRY_USER" --password-stdin >/dev/null

if [[ "$BACKEND" == "rewrite" ]]; then
  OUT_FILE="$PROJECT_ROOT/.ddev/docker-compose.private-registry.yaml"
  echo "# Auto‑generated by ddev-private-registry – DO NOT EDIT" > "$OUT_FILE"
  echo "version: '3.6'" >> "$OUT_FILE"
  echo "services:" >> "$OUT_FILE"

  if [[ -f "$CONFIG_FILE" ]]; then
    # extract lines beginning with '-' under key 'images:'
    awk '/^images:/ {f=1; next} f && /^  - / {sub(/^  - /, ""); print}' "$CONFIG_FILE" | while read -r IMG; do
      SERVICE_NAME=$(basename "$IMG" | tr ':' '_')
      printf "  %s:\n    image: %s/%s\n" "$SERVICE_NAME" "$REGISTRY_URL" "$IMG" >> "$OUT_FILE"
    done
    echo "✅ Compose override generated (rewrite backend)."
  else
    echo "⚠️  %s not found – no images rewritten." "$CONFIG_FILE"
  fi
fi
